version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/floor-management?authSource=admin
      - FRONTEND_URL=http://10.172.0.93
      - INFLUXDB_URL=http://10.172.0.84:8086
      - INFLUXDB_TOKEN=r060cSNZw
      - INFLUXDB_ORG=Global
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app      
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5000/api

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - frontend
      - backend

  mongo:
    image: mongo:6
    container_name: mongo_service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
